name: CI

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: python
        uses: actions/setup-python@v4
        with:
            python-version: "3.12"
            cache: "poetry"

      - name: install poetry
        run: pipx install poetry

      - name: install dependencies
        run: poetry install --with dev

      - name: run ruff (linting)
        run: poetry run ruff check .

      - name: run ruff (formatting check)
        run: poetry run ruff format --check .